# Generated by Django 5.0.6 on 2024-07-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0002_producto_id_category_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.URLField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
