# Generated by Django 5.0.6 on 2024-07-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0003_donacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='donacion',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
