# Generated by Django 5.0.6 on 2024-07-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0004_remove_donacion_descripcion_remove_donacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='imagen',
            field=models.URLField(default='https://example.com/default_image.jpg'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
