# Generated by Django 5.0.6 on 2024-07-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0005_donacion_imagen_alter_donacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='imagen',
            field=models.ImageField(upload_to='fundaciones/'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
