# Generated by Django 5.0.6 on 2024-07-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0007_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True),
        ),
    ]
